### ISSUE TITLE
There is no jar file and no instructions for compilation

### ISSUE THREAD

**Issue by eboileau** [bcgsc/RNA-Scoop#1]
**Describe the bug**

I downloaded and unpacked **RNA-Scoop-1.0.1.tar.gz**. 
The package has no "jar" file (RNA-Scoop.jar in the README.md), and there are no instructions on how
to build it. 

OS/version:
- Linux atlas 4.19.0-17-amd64 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux 
- java version "1.8.0_181"
- Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
- Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

Thank you.

**Comment by kmnip** [comment]
There is a JAR file in the archive, `rnascoop_v1.0.1.tar.gz`. I have just downloaded this archive from the [release](https://github.com/bcgsc/RNA-Scoop/releases/tag/v1.0.1) section and tested it myself.

As mentioned in the README, you need to extract the `tar.gz` file, i.e. with this command:
```
tar -zxf rnascoop_v1.0.1.tar.gz
```

You will then see a new directory called `rnascoop_v1.0.1`.

In this directory, you will see the JAR file, i.e.
```
LICENSE
README.md
RNA-Scoop.jar <------ THIS IS THE JAR FILE
```

**Comment by eboileau** [comment]
Thank you for your quick reply. The archive/tar files under [Releases](https://github.com/bcgsc/RNA-Scoop/releases) are different than those under [Tags](https://github.com/bcgsc/RNA-Scoop/tags), i.e. the one I got under Tags is "RNA-Scoop-1.0.1.tar.gz", and NOT "rnascoop_v1.0.1.tar.gz".
