### ISSUE TITLE
Multiple errors when trying to launch RNA-Scoop

### ISSUE THREAD

**Issue by tonyaseverson** [bcgsc/RNA-Scoop#8]
I tried launching RNA-Scoop, but after googling awhile I am still not sure how to solve the problem.

This is the java version info:

> java version "1.8.0_192"
> Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

Initially I had an exception indicating that it couldn't open a display. I realized that my alias didn't include a -Y flag, so I enabled X11 forwarding and confirmed that `xeyes` worked.  When I attempted to run again, I still had exceptions. After running ...

> java -Dprism.verbose=true -Djavafx.verbose=true -jar ~/bin/thirdparty/rnascoop_v1.0.1/RNA-Scoop.jar &> ~/logs/rnascoop.out

... I had some more info to go along with the errors - see file attached:

[rnascoop.out.pdf](https://github.com/bcgsc/RNA-Scoop/files/13399214/rnascoop.out.pdf)

It seems like several things may be going on, and I'm not sure what to try first.

**Comment by msteph11** [comment]
I might try taking on the first error in the output log (`System GPU doesn't meet the es2 pipe requirement`) to start. Can you try running the command again including `-Dprism.forceGPU=true` as well? According to https://github.com/gluonhq/gluonfx-maven-plugin/issues/318 this can fix that error. Additionally, trying to run the tool by setting up a conda environment (as described in the README.md) may also be helpful.

**Comment by tonyaseverson** [comment]
Thank you @msteph11! DRAC discourages use of conda on their servers, unfortunately, and I think they may have actually done something to make it more difficult to use it. 

I used conda to create an rnascoop environment on my MacBook Pro, but I ended up with an "Exception in Application start method". 

On DRAC, I tried using the prism.forceGPU setting, and got a little farther along, but now I'm getting java.lang.UnsatisfiedLinkErrors. Here is the full trace:

Picked up JAVA_TOOL_OPTIONS: -Xmx2g
Prism pipeline init order: es2 sw 
Using java-based Pisces rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
Loading ES2 native library ... prism_es2
Loaded /cvmfs/restricted.computecanada.ca/easybuild/software/2020/Core/java/1.8.0_192/jre/lib/ext/../amd64/libprism_es2.so from relative path
	succeeded.
GLFactory using com.sun.prism.es2.X11GLFactory
(X) Got class = class com.sun.prism.es2.ES2Pipeline
Initialized prism pipeline: com.sun.prism.es2.ES2Pipeline
JavaFX: using com.sun.javafx.tk.quantum.QuantumToolkit
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: /cvmfs/restricted.computecanada.ca/easybuild/software/2020/Core/java/1.8.0_192/jre/lib/amd64/libglass.so: /cvmfs/restricted.computecanada.ca/easybuild/software/2020/Core/java/1.8.0_192/jre/lib/amd64/libglass.so: failed to map segment from shared object
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	... 5 more
Caused by: java.lang.UnsatisfiedLinkError: /cvmfs/restricted.computecanada.ca/easybuild/software/2020/Core/java/1.8.0_192/jre/lib/amd64/libglass.so: /cvmfs/restricted.computecanada.ca/easybuild/software/2020/Core/java/1.8.0_192/jre/lib/amd64/libglass.so: failed to map segment from shared object
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
	at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:112)
	at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:120)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$static$43(GtkApplication.java:52)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.<clinit>(GtkApplication.java:51)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
	... 9 more

Thanks for any leads!

**Comment by tonyaseverson** [comment]
Looks like I can install with conda on a different DRAC server:

> ## Package Plan ##
> 
>   environment location: /home/tfsevers/mambaforge/envs/rnascoop
> 
>   added / updated specs:
>     - java-jre
> 
> 
> The following packages will be downloaded:
> 
>     package                    |            build
>     ---------------------------|-----------------
>     java-jre-8.45.14           |                0        53.6 MB  cyclus
>     ------------------------------------------------------------
>                                            Total:        53.6 MB
> 
> The following NEW packages will be INSTALLED:
> 
>   java-jre           cyclus/linux-64::java-jre-8.45.14-0

However, when I do that, activate the environment, and run rnascoop on the login node, I get this:

> (rnascoop)[tfsevers@cedar5 thirdparty]$ java -jar ./rnascoop_v1.0.1/RNA-Scoop.jar
> Error occurred during initialization of VM
> Could not allocate metaspace: 1073741824 bytes

If I run on an interactive session, I get this:

> (rnascoop)[tfsevers@cdr352 tmp]$ java -Dprism.forceGPU=true -jar ~/bin/thirdparty/rnascoop_v1.0.1/RNA-Scoop.jar
> Graphics Device initialization failed for :  es2, sw
> Error initializing QuantumRenderer: no suitable pipeline found
> java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
> 	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
> 	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:227)
> 	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:173)
> 	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
> 	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
> 	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
> 	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
> Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
> 	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
> 	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
> 	at java.lang.Thread.run(Thread.java:745)
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
> Caused by: java.lang.RuntimeException: No toolkit found
> 	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:185)
> 	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
> 	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
> 	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
> 	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
> 	... 5 more

If I then load a java module, I get the following:

> (rnascoop)[tfsevers@cdr352 tmp]$ java -Dprism.forceGPU=true -Dprism.verbose=true -Djavafx.verbose=true -jar ~/bin/thirdparty/rnascoop_v1.0.1/RNA-Scoop.jar
> Picked up JAVA_TOOL_OPTIONS: -Xmx2g
> Prism pipeline init order: es2 sw
> Using java-based Pisces rasterizer
> Using dirty region optimizations
> Not using texture mask for primitives
> Not forcing power of 2 sizes for textures
> Using hardware CLAMP_TO_ZERO mode
> Opting in for HiDPI pixel scaling
> Prism pipeline name = com.sun.prism.es2.ES2Pipeline
> Loading ES2 native library ... prism_es2
> Loaded /cvmfs/restricted.computecanada.ca/easybuild/software/2020/Core/java/1.8.0_192/jre/lib/ext/../amd64/libprism_es2.so from relative path
> 	succeeded.
> GLFactory using com.sun.prism.es2.X11GLFactory
> (X) Got class = class com.sun.prism.es2.ES2Pipeline
> GraphicsPipeline.createPipeline: error initializing pipeline com.sun.prism.es2.ES2Pipeline
> *** Fallback to Prism SW pipeline
> Prism pipeline name = com.sun.prism.sw.SWPipeline
> Loaded /cvmfs/restricted.computecanada.ca/easybuild/software/2020/Core/java/1.8.0_192/jre/lib/ext/../amd64/libprism_sw.so from relative path
> (X) Got class = class com.sun.prism.sw.SWPipeline
> Initialized prism pipeline: com.sun.prism.sw.SWPipeline
> JavaFX: using com.sun.javafx.tk.quantum.QuantumToolkit
> Loaded /cvmfs/restricted.computecanada.ca/easybuild/software/2020/Core/java/1.8.0_192/jre/lib/ext/../amd64/libglass.so from relative path
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
> Caused by: java.lang.UnsupportedOperationException: Unable to open DISPLAY
> 	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:68)
> 	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
> 	at com.sun.glass.ui.Application.run(Application.java:146)
> 	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
> 	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
> 	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
> 	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
> 	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
> 	... 5 more

Interestingly, the libglass.so library appears to load fine on this server, but on the other one, it does not.

**Comment by tonyaseverson** [comment]
This is still not working for me. Is it possible to use with X11 forwarding so the GUI can be used on a local machine and access files on a server?

**Comment by msteph11** [comment]
I'm not sure as I've never done it before, but I think it's worth a shot!

Any chance this stackoverflow post is helpful for dealing with the metaspace allocation error you had above? https://stackoverflow.com/questions/70200828/error-occurred-during-initialization-of-vm-could-not-allocate-metaspace

**Comment by msteph11** [comment]
Hmm I've never seen that error before... Does it also occur if you don't use conda to install but just download and run the jar? Worst comes to worst you could try cloning the repository and running it in IntelliJ or some other IDE. That may help with debugging any errors, and if it works you could just build your own jar from there. What version of Java do you have on your Mac?

**Comment by kmnip** [comment]
> This is still not working for me. Is it possible to use with X11 forwarding so the GUI can be used on a local machine and access files on a server?

It should work. I used to do this alot when I needed the extra RAM to run/test RNA-Scoop, e.g.
```
ssh -CX ...
```

I had a similar issue as yours when I tried to run RNA-Scoop on my WSL2 (Ubuntu) on Windows. I also installed JRE with conda.

```
$ java -Dprism.verbose=true -jar ./RNA-Scoop.jar

Prism pipeline init order: es2 sw
Using java-based Pisces rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
Loading ES2 native library ... prism_es2
GraphicsPipeline.createPipeline failed for com.sun.prism.es2.ES2Pipeline
java.lang.UnsatisfiedLinkError: /home/kmnip/miniconda3/envs/rnascoop/lib/amd64/libprism_es2.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
...
```

I was a bit lucky. Simply installing libgtk had solved the issue on my end:

```
$ sudo apt-get install libgtk2.0-0
```

**Comment by tonyaseverson** [comment]
Thank you both for your help, @msteph11 @kmnip. I finally got rnascoop running on my Mac. I have several versions of Java and I think my computer may have been defaulting to something else. The version I wanted was here:

> (base) tonyaseverson@cleo3 rnascoop_v1.0.1 % /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -version
> java version "1.8.0_391"
> Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)

When I specified the full path to the java application and ran rnascoop, the GUI appears on my screen in all its glory!: 

> (base) tonyaseverson@cleo3 rnascoop_v1.0.1 % /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -jar ~/bin/thirdparty/rnascoop_v1.0.1/RNA-Scoop.jar
> Dec 08, 2023 5:36:15 PM com.sun.glass.ui.mac.MacApplication lambda$waitForReactivation$6
> WARNING: Timeout while waiting for app reactivation

Some day I need to learn to code in Java - that would make troubleshooting a lot easier. :)

**Comment by kmnip** [comment]
Glad to hear that you figured it out!

Probably don't need to learn a new programming language to troubleshoot errors, but installing new tools/packages in a dedicated conda environment would avoid version conflicts in the future.

**Comment by tonyaseverson** [comment]
@kmnip I did install rnascoop in a dedicated conda environment (copied and pasted the command in the rnascoop README), but the payload didn't include a jar file for rnascoop. When I activated the conda environment and used the conda-supplied java to run the rnascoop tarball, I got the errors that I reported above (the ones that @msteph11 said she had not seen before).

**Comment by kmnip** [comment]
The conda commands in the README were just one possible way of installing JRE 8 and they were never meant to include the JAR file for RNA-Scoop. Some might argue that using conda was the "easiest" or the most "straightforward" method for users to install new tools, but your experience had obviously shown otherwise. Regardless, as a future reference, JRE8 can be installed with or without conda.
